//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        public int UrunId { get; set; }
        public string Baslik { get; set; }
        public string ResimYol { get; set; }
        public string Fiyat { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Yakit { get; set; }
        public string Vites { get; set; }
        public string KasaTipi { get; set; }
        public string Renk { get; set; }
        public Nullable<int> Kategori { get; set; }
        public Nullable<int> ResimId { get; set; }
    }
}
